- name: Automatic Releases
  # You may pin to the exact commit or the version.
  # uses: marvinpinto/action-automatic-releases@1369002240ebd4f758bbc69e9ae3649a5c3c2e14
  uses: marvinpinto/action-automatic-releases@v1.1.1
  with:
    # GitHub secret token
    repo_token: 
    # Git tag (for automatic releases)
    automatic_release_tag: # optional
    # Should this release be marked as a draft?
    draft: # optional
    # Should this release be marked as a pre-release?
    prerelease: # optional, default is true
    # Release title (for automatic releases)
    title: # optional
    # Assets to upload to the release
    files: # optional
